export const PRODUIT_LIST_REQUEST = 'PRODUIT_LIST_REQUEST';
export const PRODUIT_LIST_SUCCESS = 'PRODUIT_LIST_SUCCESS';
export const PRODUIT_LIST_FAIL = 'PRODUIT_LIST_FAIL';

export const PRODUIT_DETAILS_REQUEST = 'PRODUIT_DETAILS_REQUEST';
export const PRODUIT_DETAILS_SUCCESS = 'PRODUIT_DETAILS_SUCCESS';
export const PRODUIT_DETAILS_FAIL = 'PRODUIT_DETAILS_FAIL';

export const PRODUCT_CREATE_REVIEW_REQUEST = 'PRODUCT_CREATE_REVIEW_REQUEST';
export const PRODUCT_CREATE_REVIEW_SUCCESS = 'PRODUCT_CREATE_REVIEW_SUCCESS';
export const PRODUCT_CREATE_REVIEW_FAIL = 'PRODUCT_CREATE_REVIEW_FAIL';
export const PRODUCT_CREATE_REVIEW_RESET = 'PRODUCT_CREATE_REVIEW_RESET';