# Generated by Django 4.2.3 on 2023-09-07 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_review_createdat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='shippingPrice',
        ),
    ]
