# Generated by Django 4.2.3 on 2023-09-07 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_remove_shippingaddress_shippingprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_code', models.CharField(max_length=30)),
                ('is_expired', models.BooleanField(default=False)),
                ('discount_price', models.IntegerField(default=0)),
                ('minimum_amount', models.IntegerField(default=20000)),
            ],
        ),
    ]
