const produits =[
    {
        '_id': 1,
        'nom': "Girls don't cry",
        'description': "Découvrez notre tapis en violet et blanc, arborant fièrement l'imprimé 'Girls Don't Cry' dans un design en forme de cœur. Ce tapis unique incarne à la fois la douceur et la force, ajoutant une touche audacieuse à votre espace",
        'motif': 'coeur',
        'image': '../images/girls_dont_cry.jpg',
        'taille': 1,
        'matiere': "coton",
        'prix': 40000,
        'en_stock': 6,
        'evaluation': 3,
        'numEvaluations': 14,
    },
    {
        '_id': 2,
        'nom': "Emoji Souriant",
        'description': "Laissez-vous enchanter par notre tapis en forme de cercle, qui capture l'essence de la joie avec un emoji souriant. Ce tapis ludique et chaleureux apporte une dose d'énergie positive à n'importe quelle pièce.",
        'motif': 'cercle',
        'image': '../images/emoji.jpg',
        'taille': 0.5,
        'matiere': "coton",
        'prix': 20000,
        'en_stock': 0,
        'evaluation': 4.5,
        'numEvaluations': 16,
    },
    {
        '_id': 3,
        'nom': "Cactus Jack",
        'description': "Découvrez le tapis emblématique de la célèbre marque de Travis Scott, 'Cactus Jack'. Ce tapis unique en son genre présente une forme distinctive inspirée d'une croix, mais avec une touche de singularité.",
        'motif': 'croix',
        'image': '../images/cactus_jack.jpg',
        'taille': 0.75,
        'matiere': "coton",
        'prix': 35000,
        'en_stock': 5,
        'evaluation': 4,
        'numEvaluations': 27,
    },
    {
        '_id': 4,
        'nom': "Anti Social Social Club",
        'description': "Préparez-vous à faire une déclaration de style avec notre tapis imprimé 'Anti Social Social Club' de forme libre. Ce tapis incarne l'attitude rebelle et non conventionnelle de la célèbre marque, ajoutant une touche de contre-culture à votre espace. ",
        'motif': 'forme libre',
        'image': '../images/anti_social_social_club.jpg',
        'taille': 1,
        'matiere': "polyester",
        'prix': 35000,
        'en_stock': 5,
        'evaluation': 4,
        'numEvaluations': 0,
    },
    {
        '_id': 5,
        'nom': "GTA PS2",
        'description': "Découvrez notre tapis en forme de CD qui célèbre l'union parfaite entre deux icônes emblématiques : 'Grand Theft Auto' et 'PlayStation 2'. Laissez-vous séduire par cet hommage rétro-gaming qui vous transporte instantanément dans l'ère des jeux vidéo classiques. ",
        'motif': 'croix',
        'image': '../images/gta_ps2.jpg',
        'taille': 2,
        'matiere': "coton",
        'prix': 35000,
        'en_stock': 0,
        'evaluation': 2,
        'numEvaluations': 5,
    },
    {
        '_id': 6,
        'nom': "Onde",
        'description': "Découvrez notre tapis captivant qui évoque les mouvements fluides d'une onde et de lignes abstraites. Les tons vibrants de jaune et de bleu se mêlent harmonieusement, créant un contraste saisissant qui attire le regard. Ce tapis est un véritable chef-d'œuvre artistique qui apportera une sensation de mouvement et de dynamisme à votre espace.",
        'motif': 'ligne',
        'image': '../images/random_lines.jpg',
        'taille': 0.75,
        'matiere': "polyester",
        'prix': 10000,
        'en_stock': 5,
        'evaluation': 4,
        'numEvaluations': 32,
    },
]

export default produits;